[package]
name = "sol_tak_toe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
proc-macro2 = "1.0.86"
rustc_version = "0.4.0"
semver = "1.0.23"
solana-program = "=1.17.25"
